language: node_js
dist: trusty
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g yarn
  - cp config.example.js config.js
install:
  - yarn
script:
  - yarn build
  - yarn test
