language: node_js
dist: xenial
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g yarn
  - cp config.example.js config.js
install:
  - yarn
script:
  - for i in `seq 1 20`; do ps a; sleep 5; done &
  - yarn build
  - yarn test
